---
# Node.JS version to use for Estuary Web
nodejs_version: "16.x"

# Go version to use for Estuary
golang_version: '1.18.7'

# Enable this to use PostgreSQL instead of SQLite (currently Postgres is unsupported by this playbook)
sqlite_disabled: false